## Breast Cancer

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report,confusion_matrix

In [2]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()
cancer.keys()

# 569 data points with 30 features
print(cancer['data'].shape)

(569, 30)


In [3]:
# how to split data
X = cancer['data']
y = cancer['target']

X_train, X_test, y_train, y_test = train_test_split(cancer.data, cancer.target, test_size=0.3)
X_train, X_test

(array([[1.757e+01, 1.505e+01, 1.150e+02, ..., 1.456e-01, 2.756e-01,
         7.919e-02],
        [1.218e+01, 1.784e+01, 7.779e+01, ..., 5.882e-02, 2.227e-01,
         7.376e-02],
        [1.453e+01, 1.398e+01, 9.386e+01, ..., 1.069e-01, 2.606e-01,
         7.810e-02],
        ...,
        [1.989e+01, 2.026e+01, 1.305e+02, ..., 1.613e-01, 2.549e-01,
         9.136e-02],
        [1.154e+01, 1.444e+01, 7.465e+01, ..., 6.918e-02, 2.329e-01,
         8.134e-02],
        [1.359e+01, 2.184e+01, 8.716e+01, ..., 6.189e-02, 2.446e-01,
         7.024e-02]]),
 array([[1.234e+01, 1.495e+01, 7.829e+01, ..., 4.793e-02, 2.298e-01,
         5.974e-02],
        [1.650e+01, 1.829e+01, 1.066e+02, ..., 9.123e-02, 2.394e-01,
         6.469e-02],
        [1.490e+01, 2.253e+01, 1.021e+02, ..., 2.475e-01, 2.866e-01,
         1.155e-01],
        ...,
        [1.303e+01, 1.842e+01, 8.261e+01, ..., 5.013e-02, 1.987e-01,
         6.169e-02],
        [1.232e+01, 1.239e+01, 7.885e+01, ..., 9.391e-02, 2.827e-01,
   

In [4]:
# with some skip code

# Standardazie data, fit only to the training data
scaler = StandardScaler()
scaler.fit(X_train)

# Now apply the transformations to the data:
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [7]:
# with some skip code

# First step
mlp = MLPClassifier(hidden_layer_sizes=(30,30,30))

# Second step
mlp.fit(X_train_scaled, y_train)

# Third Step
predictions = mlp.predict(X_test_scaled)
predictions

array([1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1])

In [9]:
print("Confusion Matrix: \n", confusion_matrix(y_test,predictions))
print("Classification Report: \n", classification_report(y_test,predictions))

Confusion Matrix: 
 [[ 57   3]
 [  3 108]]
Classification Report: 
              precision    recall  f1-score   support

          0       0.95      0.95      0.95        60
          1       0.97      0.97      0.97       111

avg / total       0.96      0.96      0.96       171

